
#
# This file is the default set of rules to compile a Pebble project.
#
# Feel free to customize this to your needs.
#

import os.path

top = '.'
out = 'build'

include_dir = '../include/'
src_dir = '../src/'

def options(opt):
    opt.load('pebble_sdk')

def configure(cfg):
    #Load waf configurations for pebble and C++
    cfg.load('pebble_sdk')
    cfg.load('compiler_cxx')

    #Add the include directory
    cfg.env.append_value('INCLUDES',[include_dir])

def build(ctx):
    ctx.load('pebble_sdk')

    build_worker = os.path.exists('worker_src')
    binaries = []

    for p in ctx.env.TARGET_PLATFORMS:
        #set APLITE or BASALT respectively
        ctx.set_env(ctx.all_envs[p])
        ctx.set_group(ctx.env.PLATFORM_NAME)

        #build the thing
        ctx.stlib(
            source=ctx.path.ant_glob(srcdir, excl=['*psp*','*pulse*']),
            target=ctx.env.PLATFORM_NAME+'/SDL.a'
        )
